resources:
- name: git-assets
  type: git
  source:
    branch: master
    uri: https://github.com/arulvannala/concourse-workshop  #Add your git

jobs:
- name: hello
  plan:
  - task: howdy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: [" My first commit!"]
  - get: git-assets
    trigger: true
